<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="PRINHYLTPDL1861" failures="0" tests="5" name="testCases.PackageNegativeTestCases" time="0.001" errors="1" timestamp="2021-04-07T18:01:58 IST" skipped="4">
  <testcase classname="testCases.PackageNegativeTestCases" name="packageLevelMaxCharacters" time="0.001">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at pages.common.<init>(common.java:19)
at pages.packagesPageObjects.<init>(packagesPageObjects.java:152)
at testCases.PackageNegativeTestCases.packageLevelMaxCharacters(PackageNegativeTestCases.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:340)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:294)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:41)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:443)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:67)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </error>
  </testcase> <!-- packageLevelMaxCharacters -->
  <testcase classname="testCases.PackageNegativeTestCases" name="packageLevelMinimumCharacters" time="0.000">
    <skipped/>
  </testcase> <!-- packageLevelMinimumCharacters -->
  <testcase classname="testCases.PackageNegativeTestCases" name="packageLevelInvalidCharacters" time="0.000">
    <skipped/>
  </testcase> <!-- packageLevelInvalidCharacters -->
  <testcase classname="testCases.PackageNegativeTestCases" name="packageLevelPortValidations" time="0.000">
    <skipped/>
  </testcase> <!-- packageLevelPortValidations -->
  <testcase classname="testCases.PackageNegativeTestCases" name="packagePortNameValidations" time="0.000">
    <skipped/>
  </testcase> <!-- packagePortNameValidations -->
</testsuite> <!-- testCases.PackageNegativeTestCases -->
